name: .NET CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Clear NuGet cache (optionnel)
      run: dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore --force-evaluate
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    - name: Run tests
      run: dotnet test --configuration Release --logger "trx;LogFileName=TestResults.trx" --results-directory TestResults

